version: "3.9"

services:
  # Images form folder name "My-app" (Frontend)
  web:
    image: registry.nipa.cloud/todolist-app/frontend:${WEB_TAG}
    environment:
      API_BASE_URL: http://api:5000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - api  

  # Images form folder name "api" (Backend)
  api:
    image: registry.nipa.cloud/todolist-app/backend:${API_TAG}
    environment:
      PORT: "5000"
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"  
    depends_on:
      - mysql

  # Images form Docker hub
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
