apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todolist-app
<<<<<<< HEAD

labels:
  - pairs:
      app.kubernetes.io/name: todolist-app
      app.kubernetes.io/part-of: todolist-stack
    includeSelectors: true
    includeTemplates: true

=======
commonLabels:
  app.kubernetes.io/name: todolist-app
  app.kubernetes.io/part-of: todolist-stack
>>>>>>> 59213a1456619de5c2bca41a4f7a141c82926bed
resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-secret.yaml
  - mysql-storage.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml
# ให้  workflow ของ github มาเเก้ tag ในนี้
images:
  - name: registry.nipa.cloud/lun-test/frontend
    newTag: "1.0.1"
  - name: registry.nipa.cloud/lun-test/backend
    newTag: "1.0.1"
