apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todolist-app
labels:
  - pairs:
      app.kubernetes.io/name: todolist-app
      app.kubernetes.io/part-of: todolist-stack
    includeSelectors: true
    includeTemplates: true
resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-secret.yaml
  - mysql-pvc.yaml
  - mysql-initdb-config.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-secret.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml
# ให้  workflow ของ github มาเเก้ tag ในนี้
images:
  - name: registry.nipa.cloud/todolist-app/frontend
    newTag: ""
  - name: registry.nipa.cloud/todolist-app/backend
    newTag: ""
