apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todolist-app

commonLabels:
  app.kubernetes.io/name: todolist-app
  app.kubernetes.io/part-of: todolist-stack

resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-secret.yaml
  - myasql-storage.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml

# ให้  workflow ของ github มาเเก้ tag ในนี้
images:
  - name: registry.nipa.cloud/lun-test/frontend
    newTag: "1.0.0"
  - name: registry.nipa.cloud/lun-test/backend
    newTag: "1.0.0"